-- -----------------------------------------------------------------------------
-- DO NOT EDIT THIS FILE UNLESS:
-- o To customize the update
-- o To execute it manually
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- Caution messages below are not commented to make sure that
-- scripts are in the right state before to be ran manually
-- -----------------------------------------------------------------------------
CAUTION: when running manually that script make sure to
CAUTION: uncomment the line below to specify a working database
-- use database_name_xx;

-- -----------------------------------------------------------------------------
-- DROP COMMON PROCEDURES/FUNCTIONS
-- -----------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS is_admin_compatible_version;
DROP PROCEDURE IF EXISTS start_admin_update;
DROP PROCEDURE IF EXISTS stop_admin_update;
