-- ---------------------------------------------------------
-- DO NOT EDIT THIS FILE UNLESS:
-- o To customize the update
-- o To execute it manually
-- ---------------------------------------------------------



-- ---------------------------------------------------------
-- Caution messages below are not commented to make sure that
-- scripts are in the right state before to be ran manually
-- ---------------------------------------------------------
CAUTION: when running manually that script make sure to uncomment the line below to specify a working database
-- use database_name_xx;

-- ---------------------------------------------------------
-- DROP COMMON PROCEDURES/FUNCTIONS
-- ---------------------------------------------------------
DROP PROCEDURE IF EXISTS add_column_if_not_exists;
DROP PROCEDURE IF EXISTS drop_column_if_exists;
DROP PROCEDURE IF EXISTS add_primary_key_to;
DROP PROCEDURE IF EXISTS drop_primary_key_to;
DROP PROCEDURE IF EXISTS add_index_to;
DROP PROCEDURE IF EXISTS drop_index_to;
DROP PROCEDURE IF EXISTS alter_column;
DROP PROCEDURE IF EXISTS modify_column;
DROP PROCEDURE IF EXISTS rename_column;
DROP PROCEDURE IF EXISTS change_column;
