-- ---------------------------------------------------------
-- DO NOT EDIT THIS FILE UNLESS:
-- o To customize the update
-- o To execute it manually
-- ---------------------------------------------------------



-- ---------------------------------------------------------
-- Caution messages below are not commented to make sure that
-- scripts are in the right state before to be ran manually
-- ---------------------------------------------------------
CAUTION: when running manually that script make sure to uncomment the line below to specify a working database
-- use database_name_xx;
CAUTION: when running manually that script make sure to comment each lines: "DECLARE EXIT HANDLER FOR SQLEXCEPTION" (if it exists) to be sure to catch all errors
CAUTION: when running manually that script make sure to source the script common_update_initialize.sql, then admin_update_initialize.sql before
CAUTION: when running manually that script make sure to source the script admin_update_finalize.sql, then common_update_finalize.sql after

-- ---------------------------------------------------------
-- START UPDATE
-- ---------------------------------------------------------
CALL is_admin_compatible_version(27, @status, @message);
CALL start_admin_update('Yield-Man Administration Server', 28, '6.1', @status, @message);

-- ---------------------------------------------------------
-- UPDATE
-- ---------------------------------------------------------

CALL modify_column(           Database(), 'ym_databases_options', 'database_id', 'int(11) unsigned NOT NULL DEFAULT \'0\'', @status, @message);
CALL modify_column(           Database(), 'ym_nodes_options', 'node_id', 'int(11) unsigned NOT NULL DEFAULT \'0\'', @status, @message);
CALL drop_column_if_exists(   Database(), 'ym_spm_version', 'site_merge_mode', @status, @message);
CALL drop_column_if_exists(   Database(), 'ym_sya_version', 'site_merge_mode', @status, @message);
DROP TABLE IF EXISTS ym_groups_users;
DROP TABLE IF EXISTS ym_groups;
DROP TABLE IF EXISTS ym_spm_stat;
DROP TABLE IF EXISTS ym_spm_stat_param;
DROP TABLE IF EXISTS ym_spm_test;

-- ---------------------------------------------------------
-- STOP UPDATE
-- ---------------------------------------------------------
CALL stop_admin_update(@status, @message);
