-- ---------------------------------------------------------
-- DO NOT EDIT THIS FILE UNLESS: 
-- o To customize the update 
-- o To execute it manually
-- ---------------------------------------------------------



-- ---------------------------------------------------------
-- Caution messages below are not commented to make sure that 
-- scripts are in the right state before to be ran manually
-- ---------------------------------------------------------
CAUTION: when running manually that script make sure to uncomment the line below to specify a working database
-- use database_name_xx;
CAUTION: when running manually that script make sure to comment each lines: "DECLARE EXIT HANDLER FOR SQLEXCEPTION" (if it exists) to be sure to catch all errors
CAUTION: when running manually that script make sure to source the script common_update_initialize.sql before and common_update_finalize.sql after



-- ---------------------------------------------------------
-- Add columns
-- ---------------------------------------------------------
-- CALL add_column_if_not_exists(Database(), 'ym_databases_options', 'option_id', 'int(10) unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST', @status, @message);
-- CALL add_column_if_not_exists(Database(), 'ym_nodes_options', 'option_id', 'int(10) unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST', @status, @message);
-- CALL add_column_if_not_exists(Database(), 'ym_users_options', 'option_id', 'int(10) unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST', @status, @message);
-- CALL add_column_if_not_exists(Database(), 'ym_tasks_options', 'option_id', 'int(10) unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST', @status, @message);


-- ---------------------------------------------------------
-- Add primary keys 
-- ---------------------------------------------------------
CALL add_primary_key_to(Database(), 'ym_settings', 'field', @status, @message);
CALL add_primary_key_to(Database(), 'ym_databases', 'database_id', @status, @message);
CALL add_primary_key_to(Database(), 'ym_nodes', 'node_id', @status, @message);


-- ---------------------------------------------------------
-- Update ym_tasks_options for JS script
-- ---------------------------------------------------------
CALL change_column(Database(), 'ym_tasks_options', 'value', 'TEXT', @status, @message);


-- ---------------------------------------------------------
-- Change BLOB type to TEXT type
-- ---------------------------------------------------------
CALL change_column(Database(), 'ym_users_profiles', 'script_content', 'MEDIUMTEXT', @status, @message);
CALL change_column(Database(), 'ym_events', 'summary', 'MEDIUMTEXT', @status, @message);


-- ---------------------------------------------------------
-- Update DB version
-- ---------------------------------------------------------
UPDATE ym_settings SET value='4.0' WHERE field='DB_VERSION_NB';
UPDATE ym_settings SET value='15' WHERE field='DB_BUILD_NB';
