#ifndef TDR_GS_VERSION_H
#define TDR_GS_VERSION_H

// This file is included in a 100% C project.
// Do not add any Qt includes or stuff, just some defines of version

// GalaxySemi TestDataRepository plugin name and supported DB version
// GEXDB B11 (Add part_txt to xx_run)
#define GEXDB_PLUGIN_GALAXY_NAME_B11    "Quantix SQL Database [Plugin V1.6 B11]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B11   11
#define GEXDB_DB_VERSION_NAME_B11       "TDR V1.6 B11"
#define GEXDB_DB_VERSION_NB_B11         16
#define GEXDB_DB_VERSION_BUILD_B11      11
// GEXDB B12 (AZ Reports)
#define GEXDB_PLUGIN_GALAXY_NAME_B12    "Quantix SQL Database [Plugin V1.7 B12]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B12   12
#define GEXDB_DB_VERSION_NAME_B12       "TDR V1.7 B12"
#define GEXDB_DB_VERSION_NB_B12         17
#define GEXDB_DB_VERSION_BUILD_B12      12
// GEXDB B13 (SYA, Genealogy)
#define GEXDB_PLUGIN_GALAXY_NAME_B13    "Quantix SQL Database [Plugin V1.8 B13]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B13   13
#define GEXDB_DB_VERSION_NAME_B13       "TDR V1.8 B13"
#define GEXDB_DB_VERSION_NB_B13         18
#define GEXDB_DB_VERSION_BUILD_B13      13
// GEXDB B14 (custom incremental update)
#define GEXDB_PLUGIN_GALAXY_NAME_B14    "Quantix SQL Database [Plugin V1.9 B14]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B14   14
#define GEXDB_DB_VERSION_NAME_B14       "TDR V1.9 B14"
#define GEXDB_DB_VERSION_NB_B14         19
#define GEXDB_DB_VERSION_BUILD_B14      14
// GEXDB B15 (Minor/Major)
#define GEXDB_PLUGIN_GALAXY_NAME_B15    "Quantix SQL Database [Plugin V1.09 B15]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B15   15
#define GEXDB_DB_VERSION_NAME_B15       "TDR V1.09 B15"
#define GEXDB_DB_VERSION_NB_B15         109
#define GEXDB_DB_VERSION_BUILD_B15      15
// GEXDB B16 (Flexible consolidation)
#define GEXDB_PLUGIN_GALAXY_NAME_B16    "Quantix SQL Database [Plugin V2.00 B16]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B16   16
#define GEXDB_DB_VERSION_NAME_B16       "TDR V2.00 B16"
#define GEXDB_DB_VERSION_NB_B16         200
#define GEXDB_DB_VERSION_BUILD_B16      16
// GEXDB B17 (Flexible consolidation)
#define GEXDB_PLUGIN_GALAXY_NAME_B17    "Quantix SQL Database [Plugin V2.00 B17]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B17   17
#define GEXDB_DB_VERSION_NAME_B17       "TDR V2.00 B17"
#define GEXDB_DB_VERSION_NB_B17         200
#define GEXDB_DB_VERSION_BUILD_B17      17
// GEXDB B18 (TDR DB)
#define GEXDB_PLUGIN_GALAXY_NAME_B18    "Quantix SQL Database [Plugin V2.00 B18]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B18   18
#define GEXDB_DB_VERSION_NAME_B18       "TDR V2.00 B18"
#define GEXDB_DB_VERSION_NB_B18         200
#define GEXDB_DB_VERSION_BUILD_B18      18
// GEXDB B19 (Die Traceability)
#define GEXDB_PLUGIN_GALAXY_NAME_B19    "Quantix SQL Database [Plugin V2.00 B19]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B19   19
#define GEXDB_DB_VERSION_NAME_B19       "TDR V2.00 B19"
#define GEXDB_DB_VERSION_NB_B19         200
#define GEXDB_DB_VERSION_BUILD_B19      19
// GEXDB B20 (Partitioning Granularity)
#define GEXDB_PLUGIN_GALAXY_NAME_B20    "Quantix SQL Database [Plugin V2.01 B20]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B20   20
#define GEXDB_DB_VERSION_NAME_B20       "TDR V2.01 B20"
#define GEXDB_DB_VERSION_NB_B20         201
#define GEXDB_DB_VERSION_BUILD_B20      20
// GEXDB B21 (AZ Consolidation)
#define GEXDB_PLUGIN_GALAXY_NAME_B21    "Quantix SQL Database [Plugin V2.01 B21]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B21   21
#define GEXDB_DB_VERSION_NAME_B21       "TDR V2.01 B21"
#define GEXDB_DB_VERSION_NB_B21         201
#define GEXDB_DB_VERSION_BUILD_B21      21
// GEXDB B21 (AZ Consolidation)
#define GEXDB_PLUGIN_GALAXY_NAME_B22    "Quantix SQL Database [Plugin V2.01 B22]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B22   22
#define GEXDB_DB_VERSION_NAME_B22       "TDR V2.01 B22"
#define GEXDB_DB_VERSION_NB_B22         201
#define GEXDB_DB_VERSION_BUILD_B22      22
// GEXDB B23 (Linux patch)
#define GEXDB_PLUGIN_GALAXY_NAME_B23    "Quantix SQL Database [Plugin V2.01 B23]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B23   23
#define GEXDB_DB_VERSION_NAME_B23       "TDR V2.01 B23"
#define GEXDB_DB_VERSION_NB_B23         201
#define GEXDB_DB_VERSION_BUILD_B23      23
// GEXDB B24 (Secured Db)
#define GEXDB_PLUGIN_GALAXY_NAME_B24    "Quantix SQL Database [Plugin V3.00 B24]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B24   24
#define GEXDB_DB_VERSION_NAME_B24       "TDR V3.00 B24"
#define GEXDB_DB_VERSION_NB_B24         300
#define GEXDB_DB_VERSION_BUILD_B24      24
// GEXDB B25 (Pin Maps Records)
#define GEXDB_PLUGIN_GALAXY_NAME_B25    "Quantix SQL Database [Plugin V3.01 B25]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B25   25
#define GEXDB_DB_VERSION_NAME_B25       "TDR V3.01 B25"
#define GEXDB_DB_VERSION_NB_B25         301
#define GEXDB_DB_VERSION_BUILD_B25      25
// GEXDB B26 (TDR alignment after incremental changes for ASE )
#define GEXDB_PLUGIN_GALAXY_NAME_B26    "Quantix SQL Database [Plugin V3.02 B26]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B26   26
#define GEXDB_DB_VERSION_NAME_B26       "TDR V3.02 B26"
#define GEXDB_DB_VERSION_NB_B26         302
#define GEXDB_DB_VERSION_BUILD_B26      26
// GEXDB B27 (FT sublot level test&retest consolidation)
#define GEXDB_PLUGIN_GALAXY_NAME_B27    "Quantix SQL Database [Plugin V3.03 B27]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B27   27
#define GEXDB_DB_VERSION_NAME_B27       "TDR V3.03 B27"
#define GEXDB_DB_VERSION_NB_B27         303
#define GEXDB_DB_VERSION_BUILD_B27      27
// GEXDB B28 (FT intermediate consolidation)
#define GEXDB_PLUGIN_GALAXY_NAME_B28    "Quantix SQL Database [Plugin V3.03 B28]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B28   28
#define GEXDB_DB_VERSION_NAME_B28       "TDR V3.03 B28"
#define GEXDB_DB_VERSION_NB_B28         303
#define GEXDB_DB_VERSION_BUILD_B28      28
// GEXDB B29
#define GEXDB_PLUGIN_GALAXY_NAME_B29    "Quantix SQL Database [Plugin V4.00 B29]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B29   29
#define GEXDB_DB_VERSION_NAME_B29       "TDR V4.00 B29"
#define GEXDB_DB_VERSION_NB_B29         400
#define GEXDB_DB_VERSION_BUILD_B29      29
// GEXDB B30
#define GEXDB_PLUGIN_GALAXY_NAME_B30    "Quantix SQL Database [Plugin V4.00 B30]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B30   30
#define GEXDB_DB_VERSION_NAME_B30       "TDR V4.00 B30"
#define GEXDB_DB_VERSION_NB_B30         400
#define GEXDB_DB_VERSION_BUILD_B30      30
// GEXDB B31
#define GEXDB_PLUGIN_GALAXY_NAME_B31    "Quantix SQL Database [Plugin V4.01 B31]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B31   31
#define GEXDB_DB_VERSION_NAME_B31       "TDR V4.01 B31"
#define GEXDB_DB_VERSION_NB_B31         401
#define GEXDB_DB_VERSION_BUILD_B31      31

// GEXDB B32
#define GEXDB_PLUGIN_GALAXY_NAME_B32    "Quantix SQL Database [Plugin V4.02 B32]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B32   32
#define GEXDB_DB_VERSION_NAME_B32       "TDR V4.02 B32"
#define GEXDB_DB_VERSION_NB_B32         402
#define GEXDB_DB_VERSION_BUILD_B32      32

// GEXDB B33
#define GEXDB_PLUGIN_GALAXY_NAME_B33    "Quantix SQL Database [Plugin V4.03 B33]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B33   33
#define GEXDB_DB_VERSION_NAME_B33       "TDR V4.03 B33"
#define GEXDB_DB_VERSION_NB_B33         403
#define GEXDB_DB_VERSION_BUILD_B33      33

// GEXDB B34
#define GEXDB_PLUGIN_GALAXY_NAME_B34    "Quantix SQL Database [Plugin V5.00 B34]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B34   34
#define GEXDB_DB_VERSION_NAME_B34       "TDR V5.00 B34"
#define GEXDB_DB_VERSION_NB_B34         500
#define GEXDB_DB_VERSION_BUILD_B34      34

// GEXDB B35
#define GEXDB_PLUGIN_GALAXY_NAME_B35    "Quantix SQL Database [Plugin V5.01 B35]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B35   35
#define GEXDB_DB_VERSION_NAME_B35       "TDR V5.01 B35"
#define GEXDB_DB_VERSION_NB_B35         501
#define GEXDB_DB_VERSION_BUILD_B35      35

// GEXDB B36
#define GEXDB_PLUGIN_GALAXY_NAME_B36    "Quantix SQL Database [Plugin V5.01 B36]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B36   36
#define GEXDB_DB_VERSION_NAME_B36       "TDR V5.01 B36"
#define GEXDB_DB_VERSION_NB_B36         501
#define GEXDB_DB_VERSION_BUILD_B36      36

// GEXDB B37
#define GEXDB_PLUGIN_GALAXY_NAME_B37    "Quantix SQL Database [Plugin V5.02 B37]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B37   37
#define GEXDB_DB_VERSION_NAME_B37       "TDR V5.02 B37"
#define GEXDB_DB_VERSION_NB_B37         502
#define GEXDB_DB_VERSION_BUILD_B37      37

// GEXDB B38
#define GEXDB_PLUGIN_GALAXY_NAME_B38    "Quantix SQL Database [Plugin V5.02 B38]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B38   38
#define GEXDB_DB_VERSION_NAME_B38       "TDR V5.02 B38"
#define GEXDB_DB_VERSION_NB_B38         502
#define GEXDB_DB_VERSION_BUILD_B38      38

// GCORE-6330: hole for V7.4 [39 - 49]

// GEXDB B50
#define GEXDB_PLUGIN_GALAXY_NAME_B50    "Quantix SQL Database [Plugin V5.03 B50]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B50   50
#define GEXDB_DB_VERSION_NAME_B50       "TDR V5.03 B50"
#define GEXDB_DB_VERSION_NB_B50         503
#define GEXDB_DB_VERSION_BUILD_B50      50

// GEXDB B51
#define GEXDB_PLUGIN_GALAXY_NAME_B51    "Quantix SQL Database [Plugin V5.04 B51]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B51   51
#define GEXDB_DB_VERSION_NAME_B51       "TDR V5.04 B51"
#define GEXDB_DB_VERSION_NB_B51         504
#define GEXDB_DB_VERSION_BUILD_B51      51

// GCORE-7439: hole for V7.5 [52 - 59]

// GEXDB B60 (V7.6 SPM)
#define GEXDB_PLUGIN_GALAXY_NAME_B60    "Quantix SQL Database [Plugin V5.13 B60]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B60   60
#define GEXDB_DB_VERSION_NAME_B60       "TDR V5.13 B60"
#define GEXDB_DB_VERSION_NB_B60         513
#define GEXDB_DB_VERSION_BUILD_B60      60

// GEXDB B61 (V7.6 SPM Filter)
#define GEXDB_PLUGIN_GALAXY_NAME_B61    "Quantix SQL Database [Plugin V5.14 B61]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B61   61
#define GEXDB_DB_VERSION_NAME_B61       "TDR V5.14 B61"
#define GEXDB_DB_VERSION_NB_B61         514
#define GEXDB_DB_VERSION_BUILD_B61      61

// GEXDB B70 (V7.7 ADR RUN_CONSOLIDATION)
#define GEXDB_PLUGIN_GALAXY_NAME_B70    "Quantix SQL Database [Plugin V6.00 B70]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B70   70
#define GEXDB_DB_VERSION_NAME_B70       "TDR V6.0 B70"
#define GEXDB_DB_VERSION_NB_B70         600
#define GEXDB_DB_VERSION_BUILD_B70      70

// GEXDB B71 (V7.7 ADR RUN_CONSOLIDATION)
#define GEXDB_PLUGIN_GALAXY_NAME_B71    "Quantix SQL Database [Plugin V6.00 B71]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B71   71
#define GEXDB_DB_VERSION_NAME_B71       "TDR V6.0 B71"
#define GEXDB_DB_VERSION_NB_B71         600
#define GEXDB_DB_VERSION_BUILD_B71      71

// GEXDB B71 (V7.7 ADR AGGREGATION_TYPE)
#define GEXDB_PLUGIN_GALAXY_NAME_B72    "Quantix SQL Database [Plugin V6.00 B72]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B72   72
#define GEXDB_DB_VERSION_NAME_B72       "TDR V6.0 B72"
#define GEXDB_DB_VERSION_NB_B72         600
#define GEXDB_DB_VERSION_BUILD_B72      72

// GEXDB B73 (V7.7 ADR AGGREGATION_LEVEL)
#define GEXDB_PLUGIN_GALAXY_NAME_B73    "Quantix SQL Database [Plugin V6.00 B73]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B73   73
#define GEXDB_DB_VERSION_NAME_B73       "TDR V6.0 B73"
#define GEXDB_DB_VERSION_NB_B73         600
#define GEXDB_DB_VERSION_BUILD_B73      73

// GEXDB B74 (V7.7 RUN CONSOLIDATION)
#define GEXDB_PLUGIN_GALAXY_NAME_B74    "Quantix SQL Database [Plugin V7.00 B74]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B74   74
#define GEXDB_DB_VERSION_NAME_B74       "TDR V7.0 B74"
#define GEXDB_DB_VERSION_NB_B74         700
#define GEXDB_DB_VERSION_BUILD_B74      74

// GEXDB B75 (V7.7 tinyint FLAGS)
#define GEXDB_PLUGIN_GALAXY_NAME_B75    "Quantix SQL Database [Plugin V7.01 B75]"
#define GEXDB_PLUGIN_GALAXY_BUILD_B75   75
#define GEXDB_DB_VERSION_NAME_B75       "TDR V7.01 B75"
#define GEXDB_DB_VERSION_NB_B75         701
#define GEXDB_DB_VERSION_BUILD_B75      75

#define GEXDB_PLUGIN_GALAXY_NAME        GEXDB_PLUGIN_GALAXY_NAME_B75
#define GEXDB_PLUGIN_GALAXY_BUILD       GEXDB_PLUGIN_GALAXY_BUILD_B75
#define GEXDB_DB_VERSION_NAME           GEXDB_DB_VERSION_NAME_B75
#define GEXDB_DB_VERSION_NB             GEXDB_DB_VERSION_NB_B75
#define GEXDB_DB_VERSION_BUILD          GEXDB_DB_VERSION_BUILD_B75


// GS TDR DB 2 : upgraded GEXDB partial schema with new tables for events and PAT info
// used in 7.2 in SQLite
#define GS_TDR_DB_VERSION_NAME          "Quantix TDR DB version 3"
#define GS_TDR_DB_VERSION_NB            3


// RETRO COMPATIBILITY
#define GEXDB_DB_VERSION_MIN_NB         GEXDB_DB_VERSION_NB

#endif // TDR_GS_VERSION_H
