# MONITORING
SOURCES += \
    sources/monitoring/mo_y123.cpp \
    sources/monitoring/mo_wafer_export.cpp \
    sources/monitoring/mo_history.cpp \
    sources/monitoring/mo_email.cpp \
    sources/monitoring/mo_admin.cpp \
    sources/gexmo_constants.cpp \
    sources/monitoring/mo_scheduler_exec_yieldtask.cpp \
    sources/monitoring/mo_scheduler_get.cpp \
    sources/monitoring/mo_scheduler_on.cpp \
    sources/monitoring/mo_scheduler_create.cpp \
    sources/monitoring/mo_task.cpp \
    sources/monitoring/mo_scheduler_view.cpp \
    sources/monitoring/mo_scheduler_tasks_db.cpp \
    sources/monitoring/mo_scheduler_tasks_xml.cpp \
    sources/gex_pat_processing.cpp \
    sources/monitoring/mo_scheduler_gui.cpp \
    sources/tasks_manager_engine.cpp \
    sources/task.cpp \
    sources/tasks_manager_gui.cpp \
    sources/scheduler_engine.cpp \
    sources/monitoring/mo_task_create_gui.cpp \
    sources/monitoring/mo_scheduler_exec.cpp \
    sources/monitoring/mo_create_task_auto_admin.cpp \
    sources/monitoring/mo_create_task_reporting.cpp \
    sources/monitoring/mo_create_task_status.cpp \
    sources/monitoring/mo_create_task_yield_check.cpp \
    sources/monitoring/mo_create_task_outlier_removal.cpp \
    sources/monitoring/mo_create_task_pump.cpp \
    sources/monitoring/mo_widget.cpp\
    sources/task_properties.cpp \
    sources/monitoring/spm/spm_dialog.cpp \
    sources/monitoring/spm/spm_draft_widget.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_settings_widget.cpp \
    sources/monitoring/spm/spm_engine.cpp \
    sources/monitoring/spm/spm_task.cpp \
    sources/monitoring/datapump/datapump_task.cpp \
    sources/monitoring/datapump/datapump_taskdata.cpp \
    sources/monitoring/reporting/reporting_task.cpp \
    sources/monitoring/reporting/reporting_taskdata.cpp \
    sources/monitoring/status/status_task.cpp \
    sources/monitoring/status/status_taskdata.cpp \
    sources/monitoring/converter/converter_task.cpp \
    sources/monitoring/converter/converter_taskdata.cpp \
    sources/monitoring/outlierremoval/outlierremoval_task.cpp \
    sources/monitoring/outlierremoval/outlierremoval_taskdata.cpp \
    sources/monitoring/autoadmin/autoadmin_task.cpp \
    sources/monitoring/autoadmin/autoadmin_taskdata.cpp \
    sources/monitoring/trigger/trigger_task.cpp \
    sources/monitoring/pat/pat_task.cpp \
    sources/monitoring/incrementalupdate/incrementalupdate_task.cpp \
    sources/monitoring/datapump/olddatapump_task.cpp \
    sources/monitoring/trigger_pat_task.cpp \
    sources/monitoring/spm/spm_database_structure_inspector.cpp \
    sources/monitoring/spm/spm_limits_widget.cpp \
    sources/monitoring/spm/spm_prod_widget.cpp \
    sources/monitoring/spm/spm_version_widget.cpp \
    sources/monitoring/statisticalMonitoring/sm_legend_widget.cpp \
    sources/monitoring/statisticalMonitoring/sm_filter_line.cpp \
    sources/monitoring/statisticalMonitoring/sm_filters.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_engine.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_task.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_taskdata.cpp \
    sources/monitoring/statisticalMonitoring/sm_sql_table_model.cpp \
    sources/monitoring/sya/sya_engine.cpp \
    sources/monitoring/sya/sya_task.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_dialog.cpp \
    sources/monitoring/spm/spm_settings_widget.cpp \
    sources/monitoring/sya/sya_settings_widget.cpp \
    sources/monitoring/sya/sya_dialog.cpp \
    sources/monitoring/statisticalMonitoring/limits_delegate.cpp \
    sources/monitoring/statisticalMonitoring/table_item.cpp \
    sources/monitoring/statisticalMonitoring/info_widget.cpp \
    sources/monitoring/sya/sya_draft_widget.cpp \
    sources/monitoring/sya/sya_limits_widget.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_draft_widget.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_limits_widget.cpp \
    sources/monitoring/statisticalMonitoring/limits_model.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_version_widget.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_alarms_widget.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_prod_widget.cpp \
    sources/monitoring/sya/sya_prod_widget.cpp \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_manual_tests_widget.cpp \
    sources/monitoring/statisticalMonitoring/manual_limit_item.cpp \
    sources/monitoring/statisticalMonitoring/alarms_model.cpp\
    sources/monitoring/statisticalMonitoring/mo_scheduler_exec_sm.cpp \
    sources/monitoring/sya/sya_version_widget.cpp \
    sources/monitoring/yield/yield_task.cpp \
    sources/monitoring/yield/yield_taskdata.cpp

HEADERS += \
    sources/monitoring/mo_y123.h \
    sources/monitoring/mo_email.h \
    sources/monitoring/mo_admin.h \
    sources/gexmo_constants.h \
    sources/monitoring/mo_task.h \
    sources/gex_pat_processing.h \
    sources/monitoring/mo_scheduler_gui.h \
    sources/tasks_manager_engine.h \
    sources/task.h \
    sources/tasks_manager_gui.h \
    sources/scheduler_engine.h \
    sources/monitoring/mo_task_create_gui.h\
    sources/task_properties.h \
    sources/monitoring/spm/spm_dialog.h \
    sources/monitoring/spm/spm_draft_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_settings_widget.h \
    sources/monitoring/spm/spm_engine.h \
    sources/monitoring/spm/spm_task.h \
    sources/monitoring/datapump/datapump_task.h \
    sources/monitoring/datapump/datapump_taskdata.h \
    sources/monitoring/reporting/reporting_task.h \
    sources/monitoring/reporting/reporting_taskdata.h \
    sources/monitoring/status/status_task.h \
    sources/monitoring/status/status_taskdata.h \
    sources/monitoring/converter/converter_task.h \
    sources/monitoring/converter/converter_taskdata.h \
    sources/monitoring/outlierremoval/outlierremoval_task.h \
    sources/monitoring/outlierremoval/outlierremoval_taskdata.h \
    sources/monitoring/autoadmin/autoadmin_task.h \
    sources/monitoring/autoadmin/autoadmin_taskdata.h \
    sources/monitoring/trigger/trigger_task.h \
    sources/monitoring/pat/pat_task.h \
    sources/monitoring/incrementalupdate/incrementalupdate_task.h \
    sources/monitoring/datapump/olddatapump_task.h \
    sources/monitoring/trigger_pat_task.h \
    sources/monitoring/spm/spm_database_structure_inspector.h \
    sources/monitoring/spm/spm_prod_widget.h \
    sources/monitoring/spm/spm_limits_widget.h \
    sources/monitoring/spm/spm_version_widget.h \
    sources/monitoring/statisticalMonitoring/sm_filter_line.h \
    sources/monitoring/statisticalMonitoring/sm_filters.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_engine.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_task.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_taskdata.h \
    sources/monitoring/statisticalMonitoring/sm_sql_table_model.h \
    sources/monitoring/statisticalMonitoring/sm_legend_widget.h \
    sources/monitoring/sya/sya_engine.h \
    sources/monitoring/sya/sya_task.h \
    sources/monitoring/spm/spm_settings_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_dialog.h \
    sources/monitoring/sya/sya_settings_widget.h \
    sources/monitoring/sya/sya_dialog.h \
    sources/monitoring/statisticalMonitoring/limits_delegate.h \
    sources/monitoring/statisticalMonitoring/table_item.h \
    sources/monitoring/statisticalMonitoring/info_widget.h \
    sources/monitoring/sya/sya_draft_widget.h \
    sources/monitoring/sya/sya_limits_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_draft_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_limits_widget.h \
    sources/monitoring/statisticalMonitoring/limits_model.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_version_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_alarms_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_prod_widget.h \
    sources/monitoring/sya/sya_prod_widget.h \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_manual_tests_widget.h \
    sources/monitoring/statisticalMonitoring/manual_limit_item.h \
    sources/monitoring/statisticalMonitoring/alarms_model.h \
    sources/monitoring/autoadmin/mo_create_task_auto_admin.h \
    sources/monitoring/sya/sya_version_widget.h \
    sources/monitoring/yield/yield_task.h \
    sources/monitoring/yield/yield_taskdata.h

FORMS += \
    sources/monitoring/status/mo_status_dialog.ui \
    sources/monitoring/mo_scheduler_dialog.ui \
    sources/monitoring/reporting/mo_reporting_dialog.ui \
    sources/monitoring/outlierremoval/mo_outlier_removal_dialog.ui \
    sources/monitoring/converter/mo_file_converter_dialog.ui \
    sources/monitoring/datapump/mo_datapump_dialog.ui \
    sources/monitoring/autoadmin/mo_autoadmin_dialog.ui \
    sources/monitoring/mo_admin_dialog.ui \
    sources/tasks_manager_gui.ui \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_settings_widget.ui \
    sources/monitoring/statisticalMonitoring/sm_legend_widget.ui \
    sources/monitoring/statisticalMonitoring/sm_filter_line.ui \
    sources/monitoring/statisticalMonitoring/sm_filters.ui \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_dialog.ui \
    sources/monitoring/statisticalMonitoring/info_widget.ui \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_version_widget.ui \
    sources/monitoring/statisticalMonitoring/statistical_monitoring_manual_tests_widget.ui \
    sources/monitoring/statisticalMonitoring/manual_limit_item.ui \
    sources/monitoring/yield/mo_yieldcheck_dialog.ui

INCLUDEPATH += sources/monitoring/statisticalMonitoring \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/ \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/common \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/common/promis_interpreter \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/promis_interpreter/lvm_ft_subcon_data \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/promis_interpreter/lvm_ft_lotlist \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/promis_interpreter/lvm_ft \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/promis_interpreter/hvm_ft \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/promis_interpreter/hvm_wt \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_bin_mapping/sources/promis_interpreter/lvm_wt \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_std_utils/sources \
    $(DEVDIR)/galaxy_libraries/galaxy_std_libraries/qx_std_utils/sources/string_utils
