#ifndef REPORT_OPTIONS_DEFINES_HEADER
#define REPORT_OPTIONS_DEFINES_HEADER

// adv_production_yield  marker
#define REPORT_OPTIONS_ADVPRODYIELD_MARKER_TITLE 1
#define REPORT_OPTIONS_ADVPRODYIELD_MARKER_YIELD 2
#define REPORT_OPTIONS_ADVPRODYIELD_MARKER_VOLUME 4


// adv_boxplot_ex marker


// adv_boxplot field
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_LIMITS		1
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_MEAN		2
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_SIGMA		4
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_MEDIAN		8
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_CP			16
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_CPK			32
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_REPEATABILITY 64
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_EV			128
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_AV			256
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_RNR			512
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_GB			1024
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_PV			2048
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_TV			4096
#define REPORT_OPTIONS_ADVBOXPLOT_FIELD_PT			8192

// adv_datalog field
#define REPORT_OPTIONS_ADVDATALOG_FIELD_COMMENT		1
#define REPORT_OPTIONS_ADVDATALOG_FIELD_TESTNUMBER	2
// to be continued...

#define REPORT_OPTIONS_WAFER_MARKER_BIN_IN_DIE		1
#define REPORT_OPTIONS_WAFER_MARKER_DIE_RETESTED	2

#define REPORT_OPTION_STATS_FIELD_TESTNAME			1
// to be continued...

// Pareto sections to list (bits power of 2)
#define	REPORT_OPTIONS_PARETO_CP			0x1		// Display 'Cp pareto' section
#define	REPORT_OPTIONS_PARETO_CPK			0x2		// Display 'Cpk pareto' section
#define	REPORT_OPTIONS_PARETO_FAIL			0x4		// Display 'Failures pareto' section
#define	REPORT_OPTIONS_PARETO_FAILSIG		0x8		// Display 'Failures signature' section
#define	REPORT_OPTIONS_PARETO_SBIN			0x10	// Display 'Soft bin pareto' section
#define	REPORT_OPTIONS_PARETO_HBIN			0x20	// Display 'Soft bin pareto' section
#define	REPORT_OPTIONS_PARETO_ALL			0x3F	// Display all pareto sections


#endif
