(SELECT 
    'TABLE_NAME',
    'TABLE_COMMENT',
    'COLUMN_NAME',
    'COLUMN_DEFAULT',
    'COLUMN_TYPE',
    'COLUMN_KEY',
    'IS_NULLABLE',
    'EXTRA',
    'COLUMN_COMMENT'
) UNION (SELECT 
    TABLES.TABLE_NAME,
    TABLES.TABLE_COMMENT,
    COLUMNS.COLUMN_NAME,
    COLUMNS.COLUMN_DEFAULT,
    COLUMNS.COLUMN_TYPE,
    COLUMNS.COLUMN_KEY,
    COLUMNS.IS_NULLABLE,
    COLUMNS.EXTRA,
    COLUMNS.COLUMN_COMMENT
FROM
	INFORMATION_SCHEMA.TABLES
    INNER JOIN INFORMATION_SCHEMA.COLUMNS ON TABLES.TABLE_NAME=COLUMNS.TABLE_NAME AND TABLES.TABLE_SCHEMA=COLUMNS.TABLE_SCHEMA
WHERE
    TABLES.TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME , ORDINAL_POSITION INTO OUTFILE '~/Workspaces/gex_75_struct.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '
');