#ifndef GQTL_DATAKEYS_GLOBAL_H
#define GQTL_DATAKEYS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GQTL_DATAKEYS_LIBRARY)
#  define GQTL_DATAKEYSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GQTL_DATAKEYSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GQTL_DATAKEYS_GLOBAL_H
