#ifndef STATISTICAL_MONITORING_MONITORED_ITEM_UNIQUE_KEY_RULE_H
#define STATISTICAL_MONITORING_MONITORED_ITEM_UNIQUE_KEY_RULE_H

enum MonitoredItemUniqueKeyRule
{
    useNum,
    useName,
    useNumAndName
};

#endif // STATISTICAL_MONITORING_MONITORED_ITEM_UNIQUE_KEY_RULE_H
