#!/bin/bash
# ---------------------------------------------------------------------------- #
# gex-lmd
# ---------------------------------------------------------------------------- #
# chkconfig: 2345 85 15
# description: Galaxy License Manager
# processname: gex-lm

### BEGIN INIT INFO
# Provides:          gex-lmd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Galaxy License Manager
# Description:       Galaxy License Manager
### END INIT INFO

export GEX_PATH=/root/galaxy-licensemanager
export HOME=/root

procname=./gex-lm

# ---------------------------------------------------------------------------- #
# killproc
# ---------------------------------------------------------------------------- #
killproc()
{
    pid=`pgrep -f $procname`
    if [ -n "$pid" ]; then
        kill $pid >/dev/null 2>&1
    fi

    sleep 1
}

# ---------------------------------------------------------------------------- #
# Check if process is running
# ---------------------------------------------------------------------------- #
checkproc()
{
    pgrep -f $procname\$ >/dev/null
    return $?
}

# ---------------------------------------------------------------------------- #
# main
# ---------------------------------------------------------------------------- #
common=`dirname $0`/bin/common.sh
if [ -f $common ]; then
    source $common
else
    source $GEX_PATH/bin/common.sh
fi

sanitycheck $procname

setenvironment $procname

case "$1" in
    start)
        if checkproc; then
            echo "[G-INFO] Gex License Manager daemon is already running"
            exit 1
        fi
        echo "[G-INFO] Starting Gex License Manager daemon"
        cd $GEX_PATH/bin
        eval $procname
        ;;
    stop)
        if ! checkproc; then
            echo "[G-INFO] Gex License Manager daemon is not running"
            exit 1
        fi
        echo "[G-INFO] Stopping Gex License Manager daemon"
        cd $GEX_PATH/bin
        eval $procname -t
        ;;
    status)
        if checkproc; then
            echo "[G-INFO] Gex License Manager daemon is running"
        else
            echo "[G-INFO] Gex License Manager daemon is not running"
        fi
        ;;
    *)
        echo "[G-INFO] Usage: $0 {start|stop|status}"
        ;;
esac

exit 0
