#!/bin/bash
# ---------------------------------------------------------------------------- #
# gex-email
# ---------------------------------------------------------------------------- #
# chkconfig: 2345 85 15
# description: Quantix Email
# processname: gex-email / GS-Email
#
### Go through following steps for install the daemon on Linux:
### You need to be root to perform this action
#
#     o prompt> cd <install_dir>
#     o prompt> cp gex-email /etc/init.d/
#
#     REDHAT / CENTOS / FEDORA :
#     o prompt> /sbin/chkconfig gex-email on
#
#     DEBIAN / UBUNTU :
#     o prompt> update-rc.d gex-email defaults 25 15
#
### BEGIN INIT INFO
# Provides:          gex-email
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Quantix Email
# Description:       Quantix Email
### END INIT INFO

## edit these settings to ensure proper path for this env
export GEX_PATH=@@INSTALL_PATH@@
export HOME=/root
export GEX_SERVER_PROFILE=/root/serverprofile_pm

procname=./gex-email

# ---------------------------------------------------------------------------- #
# killproc
# ---------------------------------------------------------------------------- #
killproc()
{
    pid=`pgrep -f $procname\$`
    if [ -n "$pid" ]; then
        kill $pid >/dev/null 2>&1
    fi
}

# ---------------------------------------------------------------------------- #
# Check if process is running
# ---------------------------------------------------------------------------- #
checkproc()
{
    pgrep -f $procname\$ >/dev/null
    return $?
}

# ---------------------------------------------------------------------------- #
# main
# ---------------------------------------------------------------------------- #
common=`dirname $0`/bin/common.sh
if [ -f $common ]; then
    source $common
else
    source $GEX_PATH/bin/common.sh
fi

sanitycheck $procname

setenvironment $procname

case "$1" in
    start)
        if checkproc; then
            echo "[QX-INFO] Quantix Email daemon is already running"
            exit 1
        fi
        echo "[QX-INFO] Starting Quantix Email daemon"
        cd $GEX_PATH/bin
        eval $procname
        ;;
    stop)
        if ! checkproc; then
            echo "[QX-INFO] Quantix Email daemon is not running"
            exit 1
        fi
        echo "[QX-INFO] Stopping Quantix Email daemon"
        cd $GEX_PATH/bin
        eval $procname -t 2>/dev/null
        if checkproc; then
            killproc
        fi
        ;;
    status)
        if checkproc; then
            echo "[QX-INFO] Quantix Email daemon is running"
        else
            echo "[QX-INFO] Quantix Email daemon is not running"
        fi
        ;;
    *)
        echo "[QX-INFO] Usage: $0 {start|stop|status}"
        ;;
esac

exit 0
