#!/bin/bash

usage()
{
    echo "Usage: `basename $0` [-W]"
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    usage
    exit 0
fi

for i in $*; do
    if  [ $i = "-WPROPAT"   ] ||
        [ $i = "-GEXPROPAT" ] ||
        [ $i = "-WPRO"      ] ||
        [ $i = "-GEXPRO"    ] ||
        [ $i = "-GEX"       ] ||
        [ $i = "-WYM"       ] ||
        [ $i = "-WYME"      ] ||
        [ $i = "-GYM"       ] ||
        [ $i = "-GYME"      ] ||
        [ $i = "-GTM"       ]; then
        echo
        echo "'$i' argument is not allowed for PAT-Man"
        usage
        echo
        exit 1
    fi
done

source `dirname $0`/bin/common.sh
run gex -GPME $*

exit $?
