#!/bin/bash

usage()
{
    echo "Usage: `basename $0` [-W|-WYM]"
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    usage
    exit 0
fi

for i in $*; do
    if  [ $i = "-WPRO"      ] ||
        [ $i = "-GEXPRO"    ] ||
        [ $i = "-GEX"       ] ||
        [ $i = "-WPM"       ] ||
        [ $i = "-GPM"       ]; then
        echo
        echo "'$i' argument is not allowed for Yield-Man"
        usage
        echo
        exit 1
    fi
done

source `dirname $0`/bin/common.sh
run gex -GYM $*

exit $?
