--
-- First arg is the YmAdmin name
--

DEFINE GEXADMIN=%1
DEFINE GEXADMINPWD=%2


--
-- Create YMDB tablespaces
--


CREATE TABLESPACE &GEXADMIN. 
  NOLOGGING 
  DATAFILE '&GEXADMIN..dbf' SIZE 5M REUSE AUTOEXTEND 
  ON NEXT 5M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
  SEGMENT SPACE MANAGEMENT AUTO 
  DEFAULT COMPRESS;

CREATE TEMPORARY TABLESPACE &GEXADMIN._TEMP 
		TEMPFILE '&GEXADMIN._TEMP.dbf' SIZE 2000M	REUSE AUTOEXTEND 
		ON NEXT	500M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

  
--
-- Create &GEXADMIN. users
--
 
CREATE USER &GEXADMIN. PROFILE DEFAULT
 IDENTIFIED BY &GEXADMINPWD. 
 DEFAULT TABLESPACE &GEXADMIN.
 TEMPORARY TABLESPACE &GEXADMIN._temp 
 ACCOUNT UNLOCK;
GRANT CONNECT TO &GEXADMIN.;
GRANT RESOURCE TO &GEXADMIN.;
GRANT OEM_MONITOR TO &GEXADMIN.;
GRANT ALTER TABLESPACE TO &GEXADMIN.;
GRANT CREATE TABLESPACE TO &GEXADMIN.;
GRANT DROP TABLESPACE TO &GEXADMIN.;
GRANT MANAGE TABLESPACE TO &GEXADMIN.;
GRANT IMP_FULL_DATABASE TO &GEXADMIN.;
GRANT EXP_FULL_DATABASE TO &GEXADMIN.;
GRANT SCHEDULER_ADMIN TO &GEXADMIN.; 
ALTER USER &GEXADMIN. DEFAULT ROLE ALL;
GRANT CREATE JOB TO &GEXADMIN.;


--
-- Create YMDB tables and indexes
--

CREATE TABLE &GEXADMIN..ym_settings (
  field VARCHAR2(256) NOT NULL,
  value VARCHAR2(1024)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;


INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('DB_VERSION_NB','3.0');
INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('DB_BUILD_NB','12');
INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('DB_VERSION_NAME','Yield-Man Administration Server');
INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('DB_OPTIONLEVEL','5');
INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('DB_MIN_BEFORE_DISCONNECT','5');
INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('BI_SERVER',NULL);
INSERT INTO &GEXADMIN..ym_settings (field,value) VALUES ('LDAP_SERVER',NULL);

CREATE TABLE &GEXADMIN..ym_databases (
  database_id NUMBER(10) NOT NULL,
  node_id NUMBER(10),
  name VARCHAR2(256),
  description VARCHAR2(256),
  plugin_name VARCHAR2(256),
  plugin_file VARCHAR2(256),
  plugin_version VARCHAR2(256),
  host VARCHAR2(256),
  port NUMBER(8),
  driver VARCHAR2(256),
  schema VARCHAR2(256),
  database VARCHAR2(256),
  user_name VARCHAR2(256),
  user_pwd VARCHAR2(256),
  admin_name VARCHAR2(256),
  admin_pwd VARCHAR2(256),
  incremental_updates NUMBER(3),
  creation_date DATE,
  expiration_date DATE, 
  type VARCHAR2(30) DEFAULT NULL, 
  last_update DATE DEFAULT NULL, 
  mutex VARCHAR2(256) DEFAULT NULL, 
  CONSTRAINT pk_ym_databases PRIMARY KEY (database_id)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_databases_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_databases_options (
  database_id NUMBER(11) NOT NULL,
  field VARCHAR2(256) NOT NULL,
  value VARCHAR2(1024)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE TABLE &GEXADMIN..ym_groups (
  group_id NUMBER(10) NOT NULL,
  user_id NUMBER(10),
  name VARCHAR2(256),
  description VARCHAR2(256),
  profile_id NUMBER(10),
  allowed_products VARCHAR2(1024),
  allowed_lots VARCHAR2(1024),
  CONSTRAINT pk_ym_groups PRIMARY KEY (group_id)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_groups_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_groups_users (
  group_id NUMBER(10) NOT NULL,
  user_id NUMBER(10) NOT NULL
  ) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;
  
CREATE TABLE &GEXADMIN..ym_nodes (
  node_id NUMBER(10) NOT NULL,
  cpu VARCHAR2(256),
  host_name VARCHAR2(256),
  host_id VARCHAR2(256),
  os VARCHAR2(256),
  os_login VARCHAR2(256),
  gex_server_profile VARCHAR2(1024), 
  type VARCHAR2(255) DEFAULT NULL, 
  name VARCHAR2(255) DEFAULT NULL, 
  status VARCHAR2(256) DEFAULT NULL, 
  last_update DATE DEFAULT NULL, 
  mutex VARCHAR2(256) DEFAULT NULL,
  CONSTRAINT pk_ym_nodes PRIMARY KEY (node_id)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_nodes_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_nodes_options (
  node_id NUMBER(11),
  field VARCHAR2(256) NOT NULL,
  value VARCHAR2(1024)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE TABLE &GEXADMIN..ym_tasks (
  task_id NUMBER(10) NOT NULL,
  node_id NUMBER(11),
  user_id NUMBER(11),
  group_id NUMBER(11),
  database_id NUMBER(11),
  name VARCHAR2(256),
  type NUMBER(3),
  enabled NUMBER(3),
  permisions NUMBER(8),
  creation_date DATE,
  expiration_date DATE,
  last_update DATE,
  mutex VARCHAR2(256),
  CONSTRAINT pk_ym_tasks PRIMARY KEY (task_id)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_tasks_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_tasks_options (
  task_id NUMBER(10) NOT NULL,
  field VARCHAR2(256) NOT NULL,
  value VARCHAR2(4000)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;


CREATE TABLE &GEXADMIN..ym_users (
  user_id NUMBER(10) NOT NULL,
  group_id NUMBER(10),
  login VARCHAR2(256) NOT NULL,
  pwd VARCHAR2(256),
  name VARCHAR2(256),
  email VARCHAR2(256),
  type NUMBER(3) NOT NULL,
  os_login VARCHAR2(256),
  profile_id NUMBER(10),
  creation_date DATE,
  expiration_date DATE,
  last_access DATE, 
  last_update DATE DEFAULT NULL, 
  mutex VARCHAR2(256) DEFAULT NULL, 
  CONSTRAINT pk_ym_users PRIMARY KEY (user_id)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_users_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_users_options (
  user_id NUMBER(11),
  field VARCHAR2(256) NOT NULL,
  value VARCHAR2(1024)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;


CREATE TABLE &GEXADMIN..ym_users_profiles (
  profile_id NUMBER(10) NOT NULL,
  user_id NUMBER(10) NOT NULL,
  name VARCHAR2(256),
  description VARCHAR2(256),
  os_login VARCHAR2(256),
  permisions NUMBER(8),
  script_name VARCHAR2(256),
  script_content CLOB,
  creation_date DATE,
  last_update DATE,
  CONSTRAINT pk_ym_users_profiles PRIMARY KEY (profile_id)
) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_users_profiles_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_events (	
  creation_time DATE NOT NULL ENABLE, 
  event_id NUMBER(20,0) NOT NULL ENABLE, 
  link NUMBER(20,0) DEFAULT NULL, 
  category VARCHAR2(256) NOT NULL ENABLE, 
  type VARCHAR2(256) NOT NULL ENABLE, 
  start_time DATE, 
  duration NUMBER(11,0) DEFAULT 0, 
  "size" NUMBER(11,0) DEFAULT 0, 
  node_id NUMBER(11,0) DEFAULT NULL, 
  user_id NUMBER(11,0) DEFAULT NULL, 
  task_id NUMBER(11,0) DEFAULT NULL, 
  database_id NUMBER(11,0) DEFAULT NULL, 
  command VARCHAR2(1024) DEFAULT NULL, 
  status VARCHAR2(256) DEFAULT NULL, 
  summary CLOB DEFAULT NULL, 
  "comment" VARCHAR2(1024) DEFAULT NULL, 
  PRIMARY KEY (event_id) ENABLE
   ) 
  PARTITION BY RANGE (creation_time) INTERVAL (NUMTODSINTERVAL(1,'DAY')) 
 (PARTITION "FIRSTPART"  VALUES LESS THAN (TO_DATE(' 2012-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
 TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS ) ;
 
CREATE SEQUENCE &GEXADMIN..ym_events_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE &GEXADMIN..ym_actions (
  creation_time DATE NOT NULL,
  action_id NUMBER(11) NOT NULL,
  category VARCHAR2(256) NOT NULL,
  type VARCHAR2(256) NOT NULL,
  start_time DATE DEFAULT NULL,
  node_list VARCHAR2(256) DEFAULT '|',
  mutex VARCHAR2(256) DEFAULT NULL,
  task_id NUMBER(11) DEFAULT NULL,
  database_id NUMBER(11) DEFAULT NULL,
  status VARCHAR2(256) DEFAULT NULL,
  command VARCHAR2(256) DEFAULT NULL,
  PRIMARY KEY (action_id)
  ) TABLESPACE &GEXADMIN. PCTFREE 5 PCTUSED 80 COMPRESS;

CREATE SEQUENCE &GEXADMIN..ym_actions_sequence START WITH 1 INCREMENT BY 1 NOCACHE;

exit;
